import React from 'react'
import { ChevronDown, Search } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger
} from '@/components/ui/dropdown-menu'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import EmailFormModal from './EmailFormModel'

const careerCategories = [
  {
    id: 'education',
    title: 'Education',
    icon: '🎓',
 careers : [
  "Higher Education Lecturer",
  "Primary School Teacher",
  "Image Consultant",
  "Secondary School Teacher",
  "Personal Education Guide",
  "Instructional Coordinator",
  "Online Educator",
  "Education Technology Specialist",
  "Youth Worker",
  "Home Care Manager",
  "Online Tutor",
  "School Counselor",
  "College Professor",
  "Educational Consultant",
  "Homeschool Consultant",
  "Chemistry Teacher",
  "Education Administrator",
  "Historian",
  "Social Worker",
  "Nursery Teacher",
  "Nursery Worker",
  "Curriculum Developer",
  "Corporate Trainer",
  "Science Writer",
  "Program Evaluator",
  "Tech Ethicist",
  "Montessori Teacher",
  "Librarian",
  "Student Affairs Administrator",
  "Personal Privacy Advisor",
  "Learning Experience Designer",
  "Immigration Expert",
  "Problem-Solving Competition Director",
  "Teacher",
  "Special Education Teacher",
  "School Psychologist"
],

  },
  {
    id: 'ecommerce',
    title: 'E-commerce',
    icon: '🛒',
   careers : [
  "E-commerce Customer Experience Manager",
  "E-commerce Social Media Manager",
  "E-commerce Content Writer",
  "E-commerce Merchandiser",
  "E-commerce Business Development Manager",
  "E-commerce Director",
  "E-commerce Platform Manager",
  "E-commerce Logistics Coordinator",
  "E-commerce Web Developer",
  "E-commerce Specialist",
  "E-commerce SEO Specialist",
  "E-commerce Product Manager",
  "E-commerce User Experience (UX) Designer",
  "E-commerce Manager",
  "E-commerce Conversion Rate Optimization (CRO) Specialist",
  "E-commerce Analyst",
  "E-commerce Marketing Manager",
  "E-commerce Customer Service Representative",
  "E-commerce Sales Manager",
  "E-commerce Coordinator",
  "E-commerce Data Analyst",
  "E-commerce Operations Manager",
  "E-commerce Fulfillment Manager",
  "E-commerce Growth Hacker",
  "E-commerce Digital Marketing Specialist"
],

  },
  {
    id: 'cultural-heritage',
    title: 'Cultural Heritage Management',
    icon: '🏛️',
   careers : [
  "Cultural Heritage Manager",
  "Heritage Site Manager",
  "Art Historian",
  "Historic Preservationist",
  "Cultural Resource Manager",
  "Heritage Education Specialist",
  "Archaeologist",
  "Conservationist",
  "Archivist",
  "Museum Curator"
],

  },
  {
    id: 'arts-design',
    title: 'Arts and Design',
    icon: '🎨',
   careers : [
  "Stage Manager",
  "Web Developer",
  "Film Director",
  "Body Painter",
  "Art Director",
  "Graphic Designer",
  "Fashion Designer",
  "Web Designer",
  "Art Therapist",
  "Artist",
  "Dancer",
  "Product Designer",
  "Creative Director",
  "Calligrapher",
  "Print Designer",
  "Event Designer",
  "Photography (Wildlife/Nature)",
  "Illustrator",
  "Exhibit Designer",
  "Photographer",
  "Cosplayer",
  "Art Educator",
  "Interior Decorator",
  "Makeup Artist",
  "Graphic Designer/Artist",
  "Video Game Designer",
  "Screenwriter",
  "Rotoscoping Artist",
  "Musician",
  "Actor",
  "Costume Designer",
  "Cartoonist",
  "Visual Merchandiser",
  "Painter",
  "Set Designer",
  "Fine Artist",
  "Animator",
  "Animator/VFX Artist",
  "Tattoo Artist",
  "Art Installer",
  "Museum Curator",
  "3D Modeler"
],

  },
  {
    id: 'agriculture',
    title: 'Agriculture and Natural Resources',
    icon: '🌾',
  careers :[
  "Ranch Manager",
  "Land Restoration Specialist",
  "Farmer",
  "Urban Gardener",
  "Environmental Educator",
  "Agroecologist",
  "Fishery Manager",
  "Ecological Restoration Technician",
  "Horticulturist",
  "Sustainable Agriculture Specialist",
  "Veterinary Technician",
  "Plant Pathologist",
  "Environmental Consultant",
  "Forester",
  "Permaculture Designer",
  "Soil Scientist",
  "Hydroponics Specialist",
  "Aquaculture Technician",
  "Conservation Scientist",
  "Agroforestry Specialist",
  "Renewable Energy Consultant",
  "Agricultural Scientist",
  "Agricultural Inspector",
  "Wildlife Conservationist",
  "Agronomist"
],

  },
  {
    id: 'robotics',
    title: 'Robotics and Automation',
    icon: '🤖',
    careers :[
  "Robotics Account Manager",
  "Software Developer",
  "Robotics Service Technician",
  "Mechatronics Engineer",
  "VLSI Engineer",
  "Robotics Engineer",
  "Cyborg Designer",
  "Robotics System Engineer",
  "Senior Robotics Specialist",
  "Sales Engineer",
  "Robot Design Engineer",
  "Robotics Technician",
  "Robotic or Holographic Avatar Designer",
  "Flexible Manufacturing Engineer",
  "Automated Product Design Engineer"
],

  },
  {
    id: 'transportation',
    title: 'Transportation and Logistics',
    icon: '🚛',
   careers : [
  "Water Transportation Operator",
  "Ship Captain",
  "Sustainable Transport Specialist",
  "Import/Export Supervisor",
  "Transport Planner",
  "Marine Cargo Inspector",
  "Logistics Manager",
  "Distribution Manager",
  "Railroad Yard Worker",
  "Air Traffic Controller",
  "Supply Chain Analyst",
  "Rail Yard Engineer",
  "Import/Export Manager",
  "Yardmaster",
  "Flight Engineer",
  "Transportation Manager",
  "Materials Handler",
  "Warehouse Manager",
  "Locomotive Engineer",
  "Gate Operations Staff",
  "Taxi Driver",
  "Inventory Control Clerk",
  "Urban Planner",
  "Airline Pilot",
  "Train Operator",
  "Fleet Manager",
  "Motorboat Operator",
  "Transportation Attendant",
  "Packaging Engineer",
  "Transportation Analyst",
  "Fork Lift Operator",
  "Traffic Director",
  "Railroad Conductor",
  "Materials Planner",
  "Bicycle Courier",
  "Flight Instructor",
  "Travel Coordinator",
  "Traffic Clerk",
  "Production Scheduler",
  "Helicopter Pilot",
  "Traffic Supervisor",
  "Refuse and Recyclable Material Collector",
  "Ride-Sharing Driver",
  "Logistics Specialist",
  "Traffic Manager",
  "Materials Control Manager",
  "Public Transportation Bus Driver",
  "Inventory Control Supervisor",
  "Train Driver",
  "Drone Operator",
  "Materials Handling Supervisor",
  "Logistics Analyst",
  "Logistics Coordinator",
  "Marine Oiler",
  "Rail Car Repairer",
  "Railroad Brake Operator",
  "Truck Driver",
  "Train Crew Member",
  "Shipping and Receiving Clerk",
  "Train Conductor",
  "Transportation Supervisor",
  "Transportation Planner",
  "Inventory Control Analyst",
  "Inventory Control Manager",
  "Expeditor",
  "Travel Manager",
  "Merchant Navy",
  "Sailor",
  "Distribution Director",
  "Transportation Director",
  "Operations Security",
  "Transportation Broker",
  "Distribution Center Manager",
  "Marine Operator",
  "Shipping and Receiving Supervisor",
  "Logistician",
  "Pilot",
  "Package Handler",
  "Traffic/Rate Analyst",
  "Transportation Inspector",
  "Estimator",
  "Inventory Control Specialist",
  "Merchant Mariners",
  "Freight Forwarder",
  "Operations Manager",
  "Import/Export Clerk"
],

  },
  {
    id: 'business-finance',
    title: 'Business and Finance',
    icon: '💼',
     careers :[
  "Operations Manager",
  "Auditor",
  "Social Media Influencer",
  "E-commerce Specialist",
  "Sales Manager",
  "Fund Manager",
  "Brand Manager",
  "Investor Relations Manager",
  "Investment Banker",
  "Procurement Specialist",
  "Risk Manager",
  "Accountant",
  "Entrepreneur",
  "Financial Planner",
  "Corporate Strategy Manager",
  "Marketing Manager",
  "Human Resources Manager",
  "Management Consultant",
  "Tax Advisor",
  "Corporate Wellness Consultant",
  "Business Development Manager",
  "Real Estate Agent",
  "Sustainability Consultant",
  "Financial Analyst",
  "Product Manager",
  "Business Analyst"
],

  },
  {
    id: 'finance-economics',
    title: 'Finance and Economics',
    icon: '📈',
   careers : [
  "Investment Analyst",
  "Investment Manager",
  "Rural Management Specialist",
  "Financial Analyst",
  "Chartered Accountant",
  "Budget Analyst",
  "Personal Financial Advisor",
  "Insurance Underwriter",
  "Economist",
  "Purchase Manager",
  "Tax Advisor",
  "Financial Adviser",
  "Financial Planner",
  "Stock Broker",
  "Accountant",
  "Auditor",
  "Treasury Analyst",
  "Account Executive",
  "Trader",
  "Bank Manager"
],

  },
  {
    id: 'business-management',
    title: 'Business and Management',
    icon: '👔',
    careers : [
  "Quality Assurance Manager",
  "Logistics Manager",
  "Supply Chain Manager",
  "COO (Chief Operating Officer)",
  "Marketing Manager",
  "Financial Analyst",
  "Sales Manager",
  "CEO (Chief Executive Officer)",
  "Executive Director",
  "CMO (Chief Marketing Officer)",
  "General Manager",
  "Director of Operations",
  "Business Development Manager",
  "Treasurer",
  "Team Leader",
  "Vice President of Operations",
  "Operations Manager",
  "Human Resources Manager",
  "Business Analyst",
  "Account Executive",
  "Vice President of Business Development",
  "CFO (Chief Financial Officer)",
  "Management Consultant",
  "CTO (Chief Technology Officer)",
  "Product Manager",
  "Administrative Manager"
],

  },
  {
    id: 'media-communications',
    title: 'Media and Communications',
    icon: '📺',
    careers : [
  "Media Consultant",
  "Video Producer",
  "Public Relations Specialist",
  "Event Host",
  "Copywriter",
  "Film Critic",
  "Entertainment Publicist",
  "Scriptwriter",
  "Radio Host",
  "Interactive Media Designer",
  "Audiobook Narrator",
  "Press Secretary",
  "Journalist",
  "Content Writer",
  "Vlogger",
  "Photojournalist",
  "Meme Creator",
  "Podcaster",
  "Media Planner",
  "Media Relations Manager",
  "Social Media Manager",
  "Digital Content Creator",
  "Production Assistant",
  "Broadcast Technician",
  "SEO Specialist",
  "Editor",
  "Advertising Specialist",
  "Voice Actor",
  "News Anchor",
  "Communications Coordinator"
],

  },
  {
    id: 'gaming',
    title: 'Gaming Industry',
    icon: '🎮',
     careers : [
  "Game Tester",
  "Interpreter/Translator",
  "Sound Designer/Audio Engineer",
  "Game Visual Artist",
  "Narrative Designer",
  "Game Creative Director",
  "Game Modeler",
  "Game License Support Engineer",
  "Game Animator/VFX/3D/UI/UX",
  "DevOps Engineer",
  "Game Developer/Programmer",
  "Game Cinematics Director",
  "Game Level Designer",
  "Game Journalist/Critic",
  "Game Designer",
  "Game Software Engineer",
  "Game Audio Programmer",
  "Game Writer/Concept Artist"
],

  },
  {
    id: 'civil-services',
    title: 'Civil Services',
    icon: '🏛️',
     careers : [
  "Indo-Tibetan Border Police Force (ITBPF)",
  "Indian Audit and Accounts Service, Group 'A'",
  "Indian Civil Accounts Service, Group 'A'",
  "Indian Defence Accounts Service, Group 'A'",
  "Indian Information Service (Junior Grade), Group 'A'",
  "Indian Trade Service, Group 'A' (Grade III)",
  "Indian P & T Accounts & Finance Service, Group 'A'",
  "Railway Services",
  "Indian Railway Accounts Service, Group 'A'",
  "Oath Commissioner",
  "Indian Administrative Service (IAS)",
  "Indian Corporate Law Service, Group 'A'",
  "Armed Forces Headquarters Civil Service, Group ‘B’ (Section Officer’s Grade)",
  "Indian Police Service (IPS)",
  "Sashastra Seema Bal (SSB) - Border Guarding Force",
  "Indian Postal Service, Group 'A'",
  "Indian Revenue Service (Customs and Central Excise), Group 'A'",
  "Indian Railway Personnel Service, Group 'A'",
  "Civil Service Fast Streamer",
  "Indian Revenue Service (Income Tax), Group 'A'",
  "Railway Ticket Collector",
  "Indian Foreign Service (IFS)",
  "Indian Defence Estates Service, Group 'A'",
  "Assistant Security Commissioner in Railway Protection Force, Group 'A'",
  "Indian Railway Traffic Service, Group 'A'",
  "Indian Ordnance Factories Service, Group 'A' (Assistant Works Manager, Administration)",
  "US Federal Government Manager - Program Manager/Director"
],

  },
  {
    id: 'sports-recreation',
    title: 'Sports and Recreation',
    icon: '⚽',
  careers : [
  "E-sports Player",
  "Exercise Physiologist",
  "Sports Statistician",
  "Yoga Instructor",
  "Sports Medicine Physician",
  "Athletic Director",
  "Fitness Trainer",
  "Strength and Conditioning Coach",
  "Professional Athlete",
  "Sports Photographer",
  "Endurance Coach",
  "Sports Facility Manager",
  "Sports Commentator",
  "Personal Trainer",
  "Sports Agent",
  "Sports Public Relations Specialist",
  "Parkour Coach",
  "Sports Marketing Manager",
  "Sports Event Coordinator",
  "Performance Coach",
  "Sports Event Manager",
  "Scout",
  "Sports Analyst",
  "Sports Development Officer",
  "Sports Psychologist",
  "Physical Education Teacher",
  "Athletic Trainer",
  "Sports Broadcaster",
  "Sports Nutritionist",
  "Physical Therapist",
  "Equipment Manager",
  "Sports Official",
  "Referee/Umpire",
  "Adventure Sports Guide",
  "Sports Management Consultant",
  "Recreational Therapist",
  "Recreation Coordinator",
  "Sports Coach"
],

  },
  {
    id: 'environmental',
    title: 'Environmental Care',
    icon: '🌱',
    careers : [
  "Floriculture",
  "Landscape Architect",
  "Ecologist",
  "Forestry/Wildlife",
  "Energy Conservation",
  "Environmental Engineering",
  "Wildlife Conservation",
  "Environmental Consultant",
  "Horticultural Worker"
],

  },
  {
    id: 'animal-care',
    title: 'Animal Care and Farming',
    icon: '🐄',
     careers : [
  "Agricultural Engineer",
  "Dairy Technology",
  "Veterinarian",
  "Pet Grooming",
  "Agricultural Science",
  "Poultry Farming",
  "Zoologist",
  "Dairy Farming",
  "Zookeeper",
  "Urban Agriculture Specialist",
  "Sugar Technology (Production & Manufacturing)",
  "Animal Training",
  "Fishery Science",
  "Animal Care Worker",
  "Agricultural Economist",
  "Farm Manager"
],

  },
  {
    id: 'fashion',
    title: 'Fashion Industry',
    icon: '👗',
   careers : [
  "Footwear Design/Technology",
  "Assistant Apparel Merchandiser",
  "Merchandise Displayer",
  "Division Director",
  "Fashion Choreography",
  "Sample Maker",
  "Fashion Stylists and Personal Shoppers",
  "Cutter",
  "Marker",
  "Sketching Employee or Sketcher",
  "Team Leader of Sample Merchandiser",
  "Modelling",
  "Executive Trainee or Management Trainee",
  "Pattern Grader",
  "Jewellery Designer",
  "Spreader",
  "Make-Up Artist",
  "Fashion Designer",
  "Merchandising Manager",
  "Pattern Maker",
  "Sample Merchandiser",
  "Assistant Designer",
  "Production Merchandiser",
  "Merchandise Planning and Buying",
  "Senior Merchandiser",
  "Assistant Retail Buyer",
  "Leather Technology",
  "Apparel Merchandiser",
  "Asserter",
  "Retail Buyer"
],

  },
  {
    id: 'social-services',
    title: 'Social Services and Counselling',
    icon: '🤝',
    careers : [
  "Life Coach",
  "Social Service Manager",
  "Diversity and Inclusion Specialist",
  "Addictions Counselor",
  "Rehabilitation Counselor",
  "Substance Abuse Counselor",
  "Occupational Therapist",
  "Animal-Assisted Therapist",
  "Behavioral Therapist",
  "Employment Counselor",
  "Mental Health Counselor",
  "Trauma Counselor",
  "Crisis Intervention Specialist",
  "Career Counselor",
  "Domestic Violence Counselor",
  "Social Worker",
  "Grief Counselor",
  "Public Health Educator",
  "Child Welfare Worker",
  "Psychologist",
  "Family Support Specialist",
  "Community Service Manager",
  "Youth Counselor",
  "Marriage and Family Therapist",
  "School Counselor"
],

  },
  {
    id: 'sales-management',
    title: 'Sales and Management',
    icon: '📊',
     careers : [
  "Book Publishing Professional",
  "Store Manager",
  "Sales Executive",
  "Public Relations Officer",
  "Internet Marketing Manager",
  "Wholesale and Manufacturing Sales Representatives",
  "Literary Agent",
  "Public Relations Specialist",
  "Retailer",
  "Website/Art Director",
  "Consultative Salesperson",
  "Desktop Publisher",
  "Marketing Executive/Specialist/Manager",
  "Advertising Account Manager",
  "Diversity Manager",
  "Buyer",
  "Estate Agent",
  "Media Planner",
  "Market Researcher",
  "Brand Manager",
  "Advertiser",
  "Product Manager",
  "International Business/Foreign Trade"
],

  },
  {
    id: 'music-entertainment',
    title: 'Music and Entertainment',
    icon: '🎵',
   careers : [
  "Film Music Composer",
  "Rock Star",
  "Technical Sound Designer",
  "Press Agent",
  "Publicity Director",
  "Record Industry Advertising Account Executive",
  "PR Director",
  "Market Adapter",
  "Road Crew",
  "Illustrator",
  "Marketing & Promotions Coordinator",
  "Internet Advertising Representative",
  "Jingle Writer",
  "Song Plugger",
  "Recording Assistant",
  "Road Manager",
  "Booking Representative",
  "Music Licensing Coordinator",
  "Orchestrator",
  "Front End Developer",
  "Session Vocalist",
  "Sound Engineer",
  "Concert Photographer",
  "Artist Development Rep",
  "Tour Publicist",
  "Booking Manager",
  "Arranger",
  "TV Music Writer",
  "GM, Label Manager",
  "Record Producer",
  "Audio Artist",
  "Flack Agent",
  "Graphic Artist",
  "Lyricist",
  "Web Admin",
  "Music Tech",
  "Background Singer",
  "Composer",
  "Background Vocalist",
  "Internet Marketing Director",
  "Singer",
  "Jazz Musician",
  "Accompanist",
  "Merchandising Representative",
  "Album Cover Designer",
  "Production Music Writer",
  "Record Company Salesperson",
  "Music Publisher",
  "Studio Singer",
  "Audio Engineer",
  "Promotion Staffer",
  "Audio Designer",
  "House Photographer",
  "A&R Administration Representative",
  "Concert Production Manager",
  "Talent Promoter",
  "FOH Engineer",
  "Production Technician",
  "Mixing Assistant",
  "Sound Technician",
  "Nightclub Manager",
  "Director of Radio Promotions",
  "Resident Sound Technician",
  "Electrical Lighting Technician",
  "Sales Representative",
  "Artist Relations and Development Representative",
  "Marketing Rep",
  "Songwriter",
  "Audio Technician",
  "Vocalist",
  "Website Marketer",
  "Festival Producer",
  "Music Marketing Representative",
  "Production Manager",
  "Webmaster",
  "Music Mixer",
  "Guitar Tech",
  "Guitar Technician",
  "Studio Manager",
  "Creative Sound Designer",
  "Licensing Consultant",
  "Concert Tour Manager",
  "Talent Buyer",
  "Account Representative",
  "Tribute Band",
  "Festival Director",
  "Agent",
  "Roadie",
  "Music Producer",
  "Web Developer",
  "Session Musician",
  "A&R Staffer",
  "Sound Artist",
  "Floor Show Group",
  "A&R Coordinator",
  "Marketing Coordinator",
  "Transcriber",
  "Lighting Technician",
  "Field Merchandiser",
  "Record Designer",
  "Show Band",
  "Website Marketing Manager",
  "Tour Coordinator",
  "Staff Publicist",
  "Recording Group",
  "Chorus Member",
  "A&R Representative",
  "Production Show",
  "Backline Tech",
  "Licensing Representative",
  "Sound Person",
  "Keyboard Tech",
  "Lounge Band",
  "Record Promoter",
  "Mixing Engineer",
  "Recording Studio Manager",
  "Audio Mastering Engineer",
  "Music Web Designer",
  "Artist Representative",
  "Collaborative Pianist",
  "Music Photographer",
  "Commercial Music Writer",
  "Concert Promoter",
  "Instrument Tech",
  "General Manager",
  "Director of Publicity and Press Relations",
  "Stage Manager",
  "Social Media Marketing Specialist",
  "Radio Promotion Manager",
  "Sales and Marketing Manager",
  "Radio Promoter",
  "Flight Attendant",
  "Show Group",
  "Personal Manager",
  "Monitor Engineer",
  "Bar Band",
  "Lighting Engineer",
  "Professional Manager",
  "Lighting Tech",
  "Band Manager",
  "Cover Artist",
  "Tour Manager",
  "Video Game Composer",
  "Tour Director",
  "Live Sound Engineer",
  "Event Technician",
  "Booking Agent"
],

  },
  {
    id: 'hospitality-tourism',
    title: 'Hospitality and Tourism',
    icon: '🏨',
      careers : [
  "Glamping Operator",
  "Travel Agent",
  "Tour Guide",
  "Cruise Director",
  "Travel Consultant",
  "Restaurant Owner",
  "Tourism Promoter",
  "Entertainment Coordinator",
  "Concierge",
  "Sommelier",
  "Restaurant Manager",
  "Event Planner",
  "Catering Manager",
  "Front Desk Supervisor",
  "Culinary Tour Guide",
  "Chef",
  "Hotel Sales Manager",
  "Resort Manager",
  "Housekeeping Manager",
  "Bed and Breakfast Owner",
  "Bartender",
  "Adventure Travel Guide",
  "Spa Manager",
  "Hotel Manager",
  "Theme Park Designer"
],

  },
  {
    id: 'food-culinary',
    title: 'Food and Culinary Art',
    icon: '👨‍🍳',
  careers : [
  "Chef",
  "Microbiologist (Food Industry)",
  "Dietitian",
  "Herbalist (Food and Health)",
  "Food Critic",
  "Culinary Travel Consultant",
  "Menu Developer",
  "Food Chemist",
  "Chocolatier",
  "Food Marketing Specialist",
  "Food Flavor Chemist",
  "Food Service Director",
  "Food Supply Chain Manager",
  "Gourmet Food Producer",
  "Farm-to-Table Coordinator",
  "Recipe Developer",
  "Culinary Research Scientist",
  "Food Entrepreneur",
  "Food Safety Specialist",
  "Baker",
  "Ethical Chef (Sustainable Practices)",
  "Food Technology",
  "Sustainability Consultant (Food Industry)",
  "Flavor Chemistry",
  "Food Flavorist",
  "Food Historian",
  "Culinary Arts Teacher",
  "Catering Service",
  "Kitchen Designer",
  "Food Product Developer"
],

  },
  {
    id: 'sales-marketing',
    title: 'Sales and Marketing',
    icon: '📈',
      careers :[
  "Email Marketing Specialist",
  "Sales Manager",
  "Account Executive",
  "Growth Hacker",
  "Public Relations Manager",
  "Customer Relationship Manager",
  "Sales Representative",
  "Content Strategist",
  "Online Community Manager",
  "Trade Show Coordinator",
  "Marketing Analyst",
  "Lead Generation Specialist",
  "Campaign Manager",
  "Brand Manager",
  "Marketing Communications Specialist",
  "Market Research Analyst",
  "Experiential Marketer",
  "Marketing Manager",
  "SEO Specialist",
  "Social Media Strategist",
  "Digital Marketing Specialist",
  "Business Development Manager",
  "Affiliate Marketer",
  "Influencer Marketing Manager",
  "Product Manager"
],
  },
  {
    id: 'politics-law',
    title: 'Politics and Law',
    icon: '⚖️',
      careers :[
  "Forensic Accountant",
  "Assistant District Attorney",
  "Attorney General",
  "District Attorney",
  "Notary Public",
  "Judge",
  "Politician",
  "Trademark Attorney",
  "Barrister",
  "Lawyer",
  "Solicitor",
  "Patent Attorney",
  "Intellectual Property Attorney",
  "Advocate General (State Level)"
],

  },

  {
    id: 'media-performing',
    title: 'Media and Performing Arts',
    icon: '🎭',
    careers :[
  "Film Editor",
  "Musician",
  "Photographer Journalist",
  "Dancer",
  "Actor",
  "Creative Writing",
  "Disc Jockeying (DJ)",
  "Stand Up Comedy",
  "Multimedia Specialist",
  "Producer",
  "Editor",
  "Radio Jockey (RJ)",
  "Dubbing/Voice Over Artist",
  "TV/Film Producer",
  "Journalist/Mass Communication",
  "Sound Engineer",
  "Anchoring",
  "Video Jockey",
  "Blogging",
  "TV/Film Director",
  "Dance Choreographer",
  "Youtubing",
  "Cinematographer",
  "Sports Commentator",
  "Writer",
  "TV/Stage Producer",
  "Camera Operator"
]

  },
  {
    id: 'law-and-public-policy',
    title: 'Law and Public Policy',
   icon: '🏛️',
  careers : [
  'Tax Attorney',
  'Judge',
  'Intellectual Property Lawyer',
  'Mediator',
  'Public Defender',
  'Court Reporter',
  'Corporate Counsel',
  'Paralegal',
  'Public Policy Analyst',
  'Real Estate Lawyer',
  'Lawyer',
  'Compliance Officer',
  'Immigration Consultant',
  'Family Lawyer',
  'Estate Planner',
  'Law Clerk',
  'Lobbyist',
  'Legal Consultant',
  'Cyber Law Expert',
  'Legal Tech Specialist',
  'Criminal Defense Attorney',
  'Digital Privacy Consultant',
  'Employment Lawyer',
  'Legal Secretary',
],
  },
  {
    id: 'Information-Technology',
    title: 'Information Technology (IT)',
    icon: '💻',
  careers : [
  'Software Developer',
  'Digital Nomad',
  'Blockchain Developer',
  'Virtual Reality Developer',
  'IT Consultant',
  'Business Intelligence Analyst',
  'IT Project Manager',
  'Ethical Hacker',
  'IT Support Specialist',
  'UX/UI Designer',
  'AI/ML Engineer',
  'Network Administrator',
  'Cybersecurity Analyst',
  'eSports Manager',
  'Systems Administrator',
  'Software Architect',
  'Information Systems Manager',
  'DevOps Engineer',
  'Data Scientist',
  'Web Developer',
  'Systems Analyst',
  'Database Administrator',
  'IT Director',
  'IT Manager',
],


  },
  {
    id: 'Beauty-and-Personal-Care',
    title: 'Beauty and Personal Care',
    icon: '💇‍♀️',
  careers :[
  'Hair Color Specialist',
  'Beauty Educator',
  'Beauty Blogger/Influencer',
  'Beauty Product Developer',
  'Hair Stylist',
  'Eyebrow Specialist',
  'Nail Technician',
  'Salon/Spa Manager',
  'Barber',
  'Cosmetic Chemist',
  'Beauty Consultant',
  'Spa Therapist',
  'Dermatologist',
  'Lash Technician',
  'Trichologist',
  'Cosmetologist',
  'Permanent Makeup Artist',
  'Beauty Brand Manager',
  'Plastic Surgeon',
  'Aromatherapist',
  'Esthetician',
  'Massage Therapist',
  'Freelance Beauty Professional',
  'Laser Technician',
  'Makeup Artist',
],
  },

  {
    id: 'Administration-and-Management',
    title: 'Administration and Management',
    icon: '📋',
   careers :[
  'IT Manager',
  'Risk Manager',
  'Business Development Manager',
  'Customer Service Manager',
  'Facilities Manager',
  'Property Manager',
  'Corporate Trainer',
  'Chief Financial Officer (CFO)',
  'Quality Assurance Manager',
  'Chief Executive Officer (CEO)',
  'General Manager',
  'Warehouse Manager',
  'Marketing Manager',
  'Business Operations Manager',
  'Human Resources Manager',
  'Executive Assistant',
  'Vice President of Operations',
  'Training and Development Manager',
  'Operations Manager',
  'Regional Manager',
  'Chief Operating Officer (COO)',
  'Management Consultant',
  'Supply Chain Manager',
  'Sales Manager',
  'Business Administrator',
  'Administrative Assistant',
  'Business Analyst',
  'Office Manager',
  'Project Manager',
  'Logistics Manager',
  'Recruitment Manager',
  'Administrative Services Manager',
  'Administrative Manager',
  'Corporate Communication Director',
],

  },
  {
    id: 'Marketing-and-Advertising',
    title: 'Marketing and Advertising',
    icon: '📣',
   careers : [
  'Social Media Marketing',
  'Conversion Rate Optimizer',
  'Copy Writers',
  'Content Writers',
  'Market Research Analysts',
  'Search Engine Marketers',
  'Digital Content Specialist',
  'Search Engine Optimization (SEO) Executives',
  'Digital Marketing Manager',
  'Personal Brand Advisor',
  'Inbound Marketing Manager',
  'Content Marketing Manager',
  'Product Manager',
  'Reviewing',
  'Marketing Specialist',
  'Social Media Marketing Experts',
  'Internet Marketing Specialists',
],


  },
  {
    id: 'IT-and-Computer-Science',
    title: 'IT and Computer Science',
    icon: '🖥️',
  careers : [
  'Systems Analyst',
  'Virtual Reality Designer',
  'Mobile Application Developer',
  'Technology Manager',
  'Blockchain Developer',
  'Computer Networking Specialist',
  'IT Support Executive',
  'Network Engineer',
  'Software Applications Developer',
  'Nanotechnology Specialist',
  'Information Security Analyst',
  'Web Designer',
  'Business Data Intelligence Software Developer',
  'Cybersecurity Analyst',
  'Network Administrator',
  'Information Technology Systems (MIS) Executive',
  'Software Engineer',
  'DevOps Engineer',
  'Database Manager',
  'Computer Systems Analyst',
  'Games Developer',
  'Cloud Architect',
  'Health Information Technician',
  'Computer Aided Design (CAD) Specialist',
  'Ethical Hacker',
  'Web Developer',
  'App Developer',
  'Cloud Computing Specialist',
  'Computer and IT Systems Manager',
  'Augmented Reality Developer',
  'IT Security Specialist',
],



  },
  {
    id: 'Safety-Management-Services',
    title: 'Safety Management Services',
    icon: '🦺',
  careers : [
  'Corporate Safety Manager',
  'Risk Manager',
  'Safety Program Manager',
  'Ergonomist',
  'Emergency Response Coordinator',
  'Safety Manager',
  'Process Safety Engineer',
  'Safety Trainer',
  'Fire Safety Officer',
  'Safety Engineer',
  'Environmental Health and Safety (EHS) Manager',
  'Safety Analyst',
  'Hazardous Materials Specialist',
  'Safety Consultant',
  'Safety Inspector',
  'Industrial Hygienist',
  'Safety Director',
  'Safety Coordinator',
  'Health and Safety Advisor',
  'Safety Auditor',
  'Construction Safety Manager',
  'Workplace Safety Officer',
  'Occupational Health and Safety Specialist',
  'Safety Technician',
  'Compliance Officer',
],



  },
  {
    id: 'National-Security-and-Emergency-services',
    title: 'National Security and Emergency service',
    icon: '🛡️',
  careers :[
  'CBI Officer',
  'Navy Sailor',
  'Probation Officer',
  '(IAF) Indian Air Force Air Man',
  'Indian Navy',
  'Body Guard/Security Officer',
  'Private Investigators',
  'Royal Marines Commando',
  'Railway Protective Force (RPF)',
  'Central Industry Security Force (CISF)',
  'Armed Forces Pilot',
  'Railway- Technical / Non-Technical Cadre',
  'National Security Guard',
  'Prison Officer',
  'Merchant Navy',
  'Police Services',
  'CID Officer',
  'IAF Officer',
  'Border Security Force (BSF)',
  'Protection Services',
  'Detectives',
  'Firefighter',
  'Central Reserve Police Force (CRPF)',
  'Soldier',
  'Paramilitary Forces',
  'Indian Coast Guard',
  'Intelligence Officer / Service',
  'Police Officer',
  'Indian Army',
  'Paramedic',
],



  },
  {
    id: 'Travel-and-Tourism',
    title: 'Travel and Tourism',
    icon: '✈️',
 careers : [
  'Scuba Diving',
  'Museum Director',
  'Adventure Tourism',
  'Physical Education',
  'Airline Cabin Crew',
  'Sports/Physical Fitness',
  'Museum Curator',
  'Yoga Instructor/Trainer',
  'Travel Agent',
  'Air Hostess Training',
  'Adventure Sports',
  'Fitness Trainer',
  'Space Tourism Guide',
  'Personal Trainer',
],


  },
  {
    id: 'Event-Management',
    title: 'Event Management',
    icon: '🎉',
 careers :[
  'Conference Organizer',
  'End-of-Life Manager or Memorializer',
  'Event Production Manager',
  'Party Planner',
  'Event Technology Specialist',
  'Catering Manager',
  'Event Manager',
  'Venue Manager',
  'Exhibition Organizer',
  'Event Designer',
  'Meeting Planner',
  'Convention Services Manager',
  'Event Operations Manager',
  'Trade Show Coordinator',
  'Sponsorship Coordinator',
  'Corporate Event Planner',
  'Wedding Photography',
  'Event Coordinator',
  'Event Planner',
  'Festival Coordinator',
  'Event Marketing Manager',
  'Logistics Manager',
  'Event Consultant',
  'Event Sales Manager',
  'Special Events Coordinator',
  'Entertainment Manager',
  'Wedding Planner',
],



  },
  {
    id: 'Construction-and-Skilled-Trades',
    title: 'Construction and Skilled Trades',
    icon: '🏗️',
   careers : [
  'Construction Engineer',
  'Treehouse Builder',
  'Estimator',
  'Heavy Equipment Operator',
  'Landfill Worm Operator',
  'Building Inspector',
  'Green Building Consultant',
  'Wind Energy Technician',
  'Technical Architect',
  'Town Planner',
  'Glazier',
  'Smart-Building Technician',
  'Cartographer',
  'Architectural Technician',
  'Architectural Assistant',
  'Landscape Designer',
  'Architect',
  'Builder',
  'Site Operative',
  'Mason',
  'Plumber',
  'Site Engineer',
  'Surveyor',
  'Building Surveyor',
  'Business Information Management Specialist',
  '3D-Printing Technician',
  'Contracts Manager',
  'Solar Photovoltaic Installer',
  'Welder',
  'General Contractor',
  'HVAC Technician',
  'Contract Administrator',
  'Carpenter',
  'Solar Panel Installer',
  'CAD Technician',
  'Field Engineer',
  'Design Specialist',
  'Construction Equipment Operator',
  'Quantity Surveyor',
  'Solar Energy Technician',
  'Project Manager',
  'Roofer',
  'Project Surveyor',
  'Surveyor',
  'Building Trades',
  'Gaming Industry',
  'Painter',
  'Structural Engineer',
  'Construction Manager',
  'Urban Farmer',
  'Commercial Manager',
  'Project Architect',
],


  },
  {
    id: 'Science-and-Research',
    title: 'Science and Research',
    icon: '🔬',
 careers : [
  'Entomologist',
  'Gemmologist',
  'Meteorologist',
  'Extinct Species Revivalist',
  'Geoscientist',
  'Paleontologist',
  'Graphologist',
  'Marine Scientist',
  'Research Scientist',
  'Chemist',
  'Aquaculture Scientist',
  'Oenologist',
  'Microbiologist',
  'Sociologist',
  'Robotics Engineer',
  'Lexicographer',
  'Biotechnologist',
  'Anthropologist',
  'Hazardous Waste Chemist',
  'Ecologist',
  'Food Scientist',
  'Toxicologist',
  'Materials Scientist',
  'Archaeologist',
  'Environmental Scientist',
  'Geomagnetist',
  'Photonics Specialist',
  'Oceanographer',
  'Clinical Biochemist',
  'Veterinary Scientist',
  'Climate Change Analyst',
  'Statistician',
  'Biophysicist',
  'Nuclear Scientist',
  'Clinical Research Coordinator',
  'Pharmacologist',
  'Data Scientist',
  'Glaciologist',
  'Linguist',
  'Environmental Chemist',
  'Geneticist',
  'Forensic Scientist',
  'Agronomist',
  'Medical Researcher',
  'Astronaut',
  'Botanist',
  'Water Chemist',
  'Rubber Technologist',
  'Forensic Artist',
  'Soil Scientist',
  'Biologist',
  'Behavioral Scientist',
  'Political Scientist',
  'Nanotechnologist',
  'Astrobiologist',
  'Science Writer',
  'Hydrogeologist',
  'Evolutionary Biologist',
  'Epidemiologist',
  'Bioinformatics Specialist',
  'Geologist',
  'Surveyor',
  'Chemical Engineer',
  'Plant Taxonomist',
  'Lab Technician',
  'Biochemist',
  'Astronomer',
  'Analytical Chemist',
  'Geophysicist',
  'Pisciculturist',
  'Library Scientist',
  'Physicist',
  'Wildlife Biologist',
  'Geochemist',
  'Neuroscientist',
  'Archival Science/Studies',
  'Criminologist',
  'Mathematician',
  'Scientific Laboratory Technician',
  'Research Scientist (Physical Sciences)',
  'Public Health Scientist',
  'Marine Biologist',
  'Clinical Research Scientist',
],


  },
  {
    id: 'Architecture',
    title: 'Architecture',
    icon: '🏛️',
 careers : [
  'Entomologist',
  'Gemmologist',
  'Meteorologist',
  'Extinct Species Revivalist',
  'Geoscientist',
  'Paleontologist',
  'Graphologist',
  'Marine Scientist',
  'Research Scientist',
  'Chemist',
  'Aquaculture Scientist',
  'Oenologist',
  'Microbiologist',
  'Sociologist',
  'Robotics Engineer',
  'Lexicographer',
  'Biotechnologist',
  'Anthropologist',
  'Hazardous Waste Chemist',
  'Ecologist',
  'Food Scientist',
  'Toxicologist',
  'Materials Scientist',
  'Archaeologist',
  'Environmental Scientist',
  'Geomagnetist',
  'Photonics Specialist',
  'Oceanographer',
  'Clinical Biochemist',
  'Veterinary Scientist',
  'Climate Change Analyst',
  'Statistician',
  'Biophysicist',
  'Nuclear Scientist',
  'Clinical Research Coordinator',
  'Pharmacologist',
  'Data Scientist',
  'Glaciologist',
  'Linguist',
  'Environmental Chemist',
  'Geneticist',
  'Forensic Scientist',
  'Agronomist',
  'Medical Researcher',
  'Astronaut',
  'Botanist',
  'Water Chemist',
  'Rubber Technologist',
  'Forensic Artist',
  'Soil Scientist',
  'Biologist',
  'Behavioral Scientist',
  'Political Scientist',
  'Nanotechnologist',
  'Astrobiologist',
  'Science Writer',
  'Hydrogeologist',
  'Evolutionary Biologist',
  'Epidemiologist',
  'Bioinformatics Specialist',
  'Geologist',
  'Surveyor',
  'Chemical Engineer',
  'Plant Taxonomist',
  'Lab Technician',
  'Biochemist',
  'Astronomer',
  'Analytical Chemist',
  'Geophysicist',
  'Pisciculturist',
  'Library Scientist',
  'Physicist',
  'Wildlife Biologist',
  'Geochemist',
  'Neuroscientist',
  'Archival Science/Studies',
  'Criminologist',
  'Mathematician',
  'Scientific Laboratory Technician',
  'Research Scientist (Physical Sciences)',
  'Public Health Scientist',
  'Marine Biologist',
  'Clinical Research Scientist',
],


  },
  {
    id: 'Engineering',
    title: 'Engineering',
    icon: '🛠️',
careers : [
  'Metallurgical Engineer',
  'Polymer/Plastic Engineer',
  'Biotechnological Engineer',
  'Energy Engineer',
  'Transportation Engineer',
  'Textile Technologist',
  'Structural Engineer',
  'Biomedical Engineer',
  'Wind Energy Engineer',
  'Thermal Engineer',
  'Electrical Engineer',
  'Computer Engineer',
  'Telecommunication Engineer',
  'Manufacturing Scientist',
  'Geotechnical Engineer',
  'Environmental Engineer',
  'Drilling Engineer',
  'Water Resources Engineer',
  'Petroleum Engineer',
  'Civil Engineer',
  'Marine Engineer',
  'Coastal Engineer',
  'Computer Science Engineer',
  'Construction Engineer',
  'Materials Engineer',
  'Consumer Engineer',
  'Broadcast Engineer',
  'Engineering Physicist',
  'Earthquake Engineer',
  'Chemical Engineer',
  'Sustainability Consultant',
  'Mining Engineer',
  'Instrumentation Engineer',
  'Motor Vehicle Technician',
  'Genetic Engineer',
  'Communication Engineer',
  'Ceramic Engineer',
  'Industrial Engineer',
  'Lift Technology Specialist',
  'Fire Engineer',
  'Software Engineer',
  'Mechatronic Engineer',
  'Mechanical Engineer',
  'Nanotech Engineer',
  'Naval Architect',
  'Robotics Engineer',
  'Aerospace Engineer',
  'Drone Technician',
  'Engineering Manager',
  'Automobile Engineer',
  'Toy Designer',
  'Architectural Engineer',
  'Ocean Engineer',
  'Nuclear Engineer',
  'Synthetic Biology Engineer',
  'Weather Control Engineer',
],


  },
  {
    id: 'Manufacturing-and-Production',
    title: 'Manufacturing and Production',
    icon: '🏭',
 careers : [
  'Millwright',
  'Production Planner/Scheduler',
  'Production Engineering Manager',
  'Plant Human Resources Manager',
  'Boilermaker',
  'Inspector',
  'Operator',
  'Safety Coordinator',
  'Dairy Processing Equipment Operator',
  'Tool Crib Attendant',
  'Tool Room Supervisor',
  'Mechanical Designer',
  'Facilities Manager',
  'Project Manager',
  'Machine Shop Production Supervisor',
  'Product Development Engineering Manager',
  'Customer Service Representative',
  'Distribution Manager',
  'Shift Supervisor',
  'Safety Manager',
  'Woodworker',
  'Bookbinder and Bindery Worker',
  'Controller',
  'Precision Assembler',
  'Purchasing Agent/Buyer',
  'Process Engineer',
  'Power Plant Distributor',
  'Powerhouse Supervisor',
  'Production Control Clerk',
  'Printing Machine Operator',
  'Power Plant Dispatcher',
  'Waste Treatment Plant Operator',
  'Configuration Analyst',
  'Metal Worker',
  'Tool and Die Maker',
  'Product Manager',
  'Floor Assembly Supervisor',
  'Quality Assurance Manager',
  'Floor Assembler',
  'Quality Engineer',
  'Quality Control Inspector',
  'Machine Tool Cutting Operator/Tender',
  'Machine Shop Maintenance Supervisor',
  'Plant Operator',
  'Coating, Painting, and Spraying Machine Operator',
  'Warehouse Worker',
  'Process/Product Design Engineer',
  'Materials Management Supervisor',
  'Quality Control Analyst',
  'Electrician',
  'Production Worker',
  'Estimating Manager',
  'Painting and Coating Worker',
  'Material Handler',
  'Machinist',
  'Mechanical Technician',
  'Materials Manager',
  'Expediter',
  'Tool, Die, and Gauge Maker',
  'Wafer Processing Technician',
  'Operations Manager',
  'Controls Engineer',
  'Photographic Processor',
  'Electromechanical Technician',
  'Cutter',
  'Packaging Engineer',
  'CNC Operator',
  'Brazer',
  'Supplier Quality Engineer',
  'Design Engineer',
  'Electronic Technician',
  'Reliability Engineer',
  'Test Engineer',
  'Manager or Supervisor',
  'Warehouse Associate',
  'Production Control Manager',
  'Director of Quality Management',
  'Chemical Plant Operator',
  'Structural Metal Fabricator',
  'Semiconductor Processor',
  'Assembler',
  'Quality Manager',
  'Solderer',
  'Mechanical Engineer',
  'Welder',
  'Production Painter',
  'Product Marketing Analyst',
  'General Laborer',
  'Process Operator',
  'Equipment Technician',
  'Assistant Plant Manager',
  'Fiberglass Laminator/Fabricator',
  'Computer Control Programmer/Operator',
  'Plant Accountant',
  'Production Technician',
  'Shipping and Receiving Manager',
  'Aircraft Mechanic',
  'Surface Mount Technology Machine Operator',
  'Manufacturing Production Manager',
  'Processing Equipment Operations Supervisor',
  'General Manager',
  'Designer',
  'Manufacturing Process Engineer',
  'Field Service Technician',
  'Stationary Engineer',
  'Assembly Supervisor',
  'Plant Manager',
  'Materials Planner',
  'Machine Operator',
  'Boiler Operator',
  'Division Manager',
  'Processing Worker',
  'Production Manager',
  'Manufacturing Technician',
  'Quality Assurance Engineer',
  'Power Plant Operator',
  'Safety Technician',
  'Chief Quality Control Executive',
  'CNC Machinist',
  'Senior Buyer',
  'Chief Manufacturing Executive',
  'Warehouse Manager',
  'Fabricator',
  'Electronic Assembler',
  'Manufacturing Engineer',
  'Master Scheduler',
  'Production Supervisor',
  'Silicon Wafer Fabrication Operator',
  'Operations Clerk',
  'Industrial Engineer',
  'Industrial Engineering Technician',
  'Production Foreman',
  'Plastic Machine Worker',
],


  },
  {
    id: 'Hospitality-Industry',
    title: ' Hospitality Industry',
    icon: '🏨',
  careers : [
  "Hotel Manager",
  "Finance",
  "Bartending",
  "Beauty Therapist",
  "Sommelier (Transport/carry wine)",
  "Concierge",
  "Hotel Management",
  "SPA Management",
  "Event Management",
  "Accountant",
  "Training and Development",
  "Catering Manager",
  "Chef and Culinary artists",
  "Tour Guiding",
  "Marketing, sales and Advertising"
],



  },
  {
    id: 'Healthcare-and-Medicine',
    title: 'Healthcare and Medicine',
    icon: '🩺',
   careers : [
  "Pathologist",
  "Veterinarian",
  "Orthopaedic Surgeon",
  "Rheumatologist",
  "Chromotherapy Specialist",
  "Hygienist",
  "Osteopathic Medicine Practitioner",
  "Otolaryngologist (ENT)",
  "Doctor",
  "Registered Nurse (RN)",
  "Nutritionist",
  "Trichologist",
  "Remote Healthcare Engineer",
  "Histopathologist",
  "Microbiologist",
  "Gastroenterologist",
  "Digital Rehab Counselor",
  "Brain Implant Specialist",
  "Rehabilitation Specialist",
  "Naturopath",
  "Custom Body Part Manufacturer",
  "Medical Coder",
  "Dental Hygienist",
  "Medical Laboratory Technician",
  "Occupational Therapist",
  "Counselor",
  "Mind Transfer Specialist",
  "Hydrotherapist",
  "Urologist",
  "Psychiatrist",
  "Genetic Counselor",
  "Home Health Aide",
  "Health Informatics Specialist",
  "Hearing Aids Specialist",
  "Plastic Surgeon",
  "Nephrologist",
  "General Surgeon",
  "Doula",
  "Pharmacist",
  "Neurological Surgeon",
  "Midwife",
  "Acupressure Therapist",
  "Reflexologist",
  "Oncologist",
  "Physical Therapist",
  "Prosthetics and Orthotics Specialist",
  "Aromatherapist",
  "Radiographer/Radiologist",
  "Surgeon",
  "Medical Radiation Therapist",
  "Space Nurse/Physician",
  "Dance Therapist",
  "Physician Assistant",
  "Alternative Healthcare Professional",
  "Podiatrist",
  "Dental Technologist",
  "Personal Microbiome Manager",
  "Hematologist",
  "X-ray Technician",
  "Pharmacovigilance Specialist",
  "Nurse",
  "Orthodontist",
  "Unani Medicine Practitioner",
  "Internal Medicine Specialist",
  "Nuclear Medicine Specialist",
  "Medical and Health Service Manager",
  "Thoracic Surgeon",
  "Virologist",
  "Pharmaceutical Artisan",
  "Holistic Health Practitioner",
  "Cognitive-Behavioral Therapist",
  "Respiratory Therapist",
  "Prosthodontist",
  "Neurologist",
  "Anesthesiologist",
  "Acupuncturist",
  "Optician & Refractionist",
  "Optometrist",
  "Art Therapist",
  "Ophthalmologist",
  "Psychologist",
  "Pharmacy Technician",
  "Physiotherapist",
  "Biomechanical Technician",
  "Music Therapist",
  "Hearing Aids Marketer",
  "Audiologist",
  "Medical Technologist",
  "Electrologist/Electrolysis Specialist",
  "Dermatologist",
  "Radiation Protection Practitioner",
  "Oral and Maxillofacial Surgeon",
  "Hospital Manager",
  "Health Services Manager",
  "Speech and Language Therapist",
  "Dental Assistant",
  "Clinical Nutritionist",
  "Dialysis Technician",
  "Radiologic Technologist",
  "Pediatrician",
  "Obstetrician/Gynecologist",
  "Ayurvedic Medicine Practitioner",
  "Surgical Technologist",
  "Super Specialty in Diplomate of National Board (DNB)",
  "Homeopath",
  "Public Health Specialist",
  "Gerontologist",
  "Medical Tourism Specialist",
  "Environmental Psychologist",
  "Speech Pathologist",
  "Management Dietitian/Nutritionist",
  "Plant Pathologist",
  "Magnetic Therapist",
  "Operation Theatre Technician",
  "Perfusionist",
  "Cardiologist",
  "Clinical Psychologist",
  "Community Nutritionist",
  "Dentist",
  "Licensed Practical and Vocational Nurses",
  "General Practitioner",
  "Medical Transcriptionist",
  "Pharmaceutical Technologist",
  "Ayurvedic Doctor",
  "Healthcare Administrator"
],


  },
  {
    id: 'Textile-and-Clothing-Industry',
    title: 'Textile and Clothing Industry',
    icon: '🧵',
   careers :[
  "Supervisor",
  "Textile Advertising And Promotion Agent",
  "Spreader",
  "Industrial Engineer",
  "Assistant Production Officer",
  "Machine Operator",
  "Production Supervisor",
  "Senior Production Officer",
  "Market Analyst",
  "Traveling Sales Representative",
  "Sales Manager",
  "Textile Sales Representative",
  "Sericulture",
  "Quality Control Inspector",
  "Pattern Maker",
  "Trimmer And Inspector",
  "Production Manager",
  "Public Relations Agent",
  "Showroom Person",
  "Textile Sales Manager",
  "Market Researcher",
  "Training Supervisor",
  "Presser or iron Operator",
  "Floor In charge",
  "Packer",
  "Textile Research Scientist",
  "Order Picker",
  "Machine Technician",
  "Showroom Manager",
  "Checker",
  "Production Officer",
  "Purchasing Agent",
  "Shift In-charge",
  "Business Planner",
  "Accounting And Finance Employee",
  "Assistant General Manager",
  "Cutter",
  "Asserter",
  "Marker",
  "Textile Designer",
  "Sales Manager",
  "Plant Engineer",
  "Assistant Production Manager",
  "Personnel Administrator",
  "Sewing Machine Operator",
  "Data Processing Employee",
  "Pattern Grader",
  "Showroom Sales Trainee",
  "Textile Laboratory Technician",
  "Transportation Specialist",
  "General Manager",
  "Finishing quality control"
],


  },
  
]

const CareerLibrary: React.FC = () => {
  return (
    <div className='min-h-screen bg-background'>
      <Header />

      <main className='py-16 bg-gradient-to-br from-background to-secondary/20'>
        <div className='container mx-auto px-4'>
          <div className='max-w-6xl mx-auto'>
            {/* Hero Section */}
            <div className='text-center mb-12'>
              <h1 className='text-5xl font-bold text-foreground mb-6'>
                Career{' '}
                <span className='bg-gradient-primary bg-clip-text text-transparent'>
                  Library
                </span>
              </h1>
              <p className='text-xl text-muted-foreground mb-8 max-w-3xl mx-auto'>
                Explore over 800+ career opportunities across 24 different
                fields. Discover your passion and find the perfect career path
                with our comprehensive career library.
              </p>

              {/* Search Bar */}
              <div className='relative max-w-lg mx-auto mb-8'>
                <Search className='absolute left-4 top-1/2 transform -translate-y-1/2 text-muted-foreground h-5 w-5' />
                <Input
                  type='text'
                  placeholder='Search careers by name or field...'
                  className='pl-12 pr-4 py-4 text-lg rounded-xl border-2 bg-background/50 backdrop-blur-sm'
                />
              </div>

              <p className='text-sm text-muted-foreground'>
                Click on any field below to explore all available career options
              </p>
            </div>

            {/* Career Categories Grid */}
  <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6'>
  {careerCategories.map(category => {
    const [isOpen, setIsOpen] = React.useState(false);

    return (
      <DropdownMenu key={category.id} open={isOpen} onOpenChange={setIsOpen}>
        <DropdownMenuTrigger asChild>
          <Button
            variant='outline'
            className='h-auto p-6 justify-start bg-card hover:bg-accent hover:text-accent-foreground transition-all duration-300 group shadow-md hover:shadow-lg border-2 hover:border-primary/30 w-[380px]'
            onMouseEnter={() => setIsOpen(true)}
            onMouseLeave={() => setIsOpen(false)}
          >
            <div className='flex items-center space-x-4 w-full'>
              <div className='text-3xl group-hover:scale-110 transition-transform duration-300'>
                {category.icon}
              </div>

              <div className='flex-1 text-left w-max'>
                <h3 className='font-semibold text-base mb-1'>
                  {category.title}
                </h3>
                <p className='text-sm text-muted-foreground'>
                  {category.careers.length}+ Career Options
                </p>
              </div>

              <ChevronDown className='h-5 w-5 group-hover:rotate-180 transition-transform duration-300 text-primary' />
            </div>
          </Button>
        </DropdownMenuTrigger>

        <DropdownMenuContent
          className='w-96 max-h-96 overflow-y-auto bg-popover border-2 shadow-xl rounded-xl'
          align='start'
          sideOffset={8}
          onMouseEnter={() => setIsOpen(true)}
          onMouseLeave={() => setIsOpen(false)}
        >
          <div className='p-3 border-b border-border bg-muted/30'>
            <h4 className='font-semibold text-foreground flex items-center gap-2'>
              <span className='text-lg'>{category.icon}</span>
              {category.title} Careers
            </h4>
            <p className='text-xs text-muted-foreground mt-1'>
              {category.careers.length} career options available
            </p>
          </div>
          {category.careers.map((career, index) => (
            <DropdownMenuItem
              key={index}
              className='cursor-pointer hover:bg-accent hover:text-accent-foreground py-3 px-4 transition-colors duration-200'
            >
              <span className='text-sm font-medium'>{career}</span>
            </DropdownMenuItem>
          ))}
        </DropdownMenuContent>
      </DropdownMenu>
    );
  })}
</div>



            {/* Additional Info Section */}
            <div className='mt-16 text-center'>
              <div className='bg-card border-2 border-primary/10 rounded-2xl p-8 max-w-4xl mx-auto'>
                <h2 className='text-2xl font-bold text-foreground mb-4'>
                  Need Personalized Career Guidance?
                </h2>
                <p className='text-muted-foreground mb-6'>
                  Our expert career counselors can help you identify the perfect
                  career path based on your interests, skills, and aspirations.
                </p>

                <EmailFormModal
                  trigger={
                    <Button className='bg-gradient-primary hover:opacity-90 transition-opacity text-lg px-8 py-3'>
                      Book Free Consultation
                    </Button>
                  }
                />
              </div>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}

export default CareerLibrary
